// Generated by tools/pipeline/fetch_balls.py; do not edit.
// Crystal 7a7881d0d62e0ddbd82dcf10e7116807487ac651: pokeball.png, BallColors, battle_anims.pal.
// Source shape is shared by all kinds; 3 is transparent. UI art is already 2x.
#pragma once
#include <stdbool.h>
#include <stdint.h>
typedef struct { uint8_t x, y, w, h; } ball_asset_bounds_t;
enum { BALL_ASSET_WIDTH = 32, BALL_ASSET_HEIGHT = 32, BALL_ASSET_KINDS = 8 };
// kind order matches the eight CAP_BALL / ITEM ball enum values.
static inline const uint16_t *ball_assets_palette(uint8_t kind)
{
    static const uint16_t palettes[8][4] = {
        {0x0000, 0xf286, 0xfcf8, 0xffff},
        {0x0000, 0x091f, 0x431f, 0xffff},
        {0x0000, 0xfc21, 0xffe7, 0xffff},
        {0x0000, 0x2b80, 0x6661, 0xffff},
        {0x0000, 0x091f, 0x431f, 0xffff},
        {0x0000, 0x6b4d, 0xce79, 0xffff},
        {0x0000, 0xa3c3, 0xc4a7, 0xffff},
        {0x0000, 0xfc21, 0xffe7, 0xffff},
    };
    return palettes[kind < 8 ? kind : 0];
}
static inline ball_asset_bounds_t ball_assets_visible(bool opened)
{
    return opened ? (ball_asset_bounds_t){4, 0, 24, 32}
                  : (ball_asset_bounds_t){4, 8, 24, 24};
}
